version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: MySecr3tPassWord@as2      
      POSTGRES_DB: ChallengeDB
    container_name: challengeGonzalo
    volumes:
      - /data